apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goodbirdacr.azurecr.io/medical/back
  newName: goodbirdacr.azurecr.io/medical/back
  newTag: v1.0.Beta16
- name: goodbirdacr.azurecr.io/medicine/back
  newName: goodbirdacr.azurecr.io/medicine/back
  newTag: v1.0.Beta106
- name: goodbirdacr.azurecr.io/medicine/front
  newName: goodbirdacr.azurecr.io/medicine/front
  newTag: latest
